name: Debian Unstable

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  debian:
    runs-on: ubuntu-latest
    container:
      image: debian:unstable

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Packages
        run: |
          apt update
          apt install sudo neofetch tmate aria2 curl wget -y

      - name: Generate Tmate Session
        run: |
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt

      - name: Ignore this
        run: |
          while true; do sleep 1; done
