name: Debian Stable

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: debian:stable

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Packages
        run: |
          apt update
          apt install sudo neofetch tmate aria2c curl wget-y

      - name: Generate Tmate Session
        run: |
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt
      
      - name: Spam
        run: |
          sudo bash spam.sh
