name: Fedora

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo dnf update -y
          sudo dnf install -y git curl wget bash neofetch aria2 tmate

      - name: Generate Tmate Session
        run: |
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt
      
      - name: Spam
        run: |
          sudo bash spam.sh
